[project]
name = "discord_bot"
version = "0.1.0"
description = "A Class built discord bot with logging"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "async>=0.6.2",
    "discord>=2.3.2",
]
